// web/src/components/UserImage.vue
<script setup lang="ts">
  import { IKImage } from 'imagekitio-vue'
  import { env } from '@/utilities'

  const { imageUrl } = defineProps<{
    imageUrl?: string,
  }>()
</script>

<template>
  <IKImage class="player-image" :url-endpoint="env().imagekitUrl" :path="`/players/${imageUrl ?? 'default.png'}`" :transformation="[{ raw: 'fo-face,r-max' }]" />
</template>

<style>
.player-image {
  border-radius: 50%;
  background-color: darkgray;
}
</style>

// mobile/src/components/UserImage.tsx
import { DimensionValue, Image, StyleSheet } from 'react-native'
import { config } from '@/config/env'
import ImageKit from 'imagekit-javascript'

export function UserImage({ imageUrl, width = '100%', height = '100%' }: { imageUrl?: string, width?: DimensionValue, height?: DimensionValue }): React.ReactNode {
  const imagekit = new ImageKit({
    urlEndpoint: config.imageKitUrl,
    publicKey: config.imageKitPublicKey,
  })
  const uri = imagekit.url({
    path: `/players/${imageUrl ?? 'default.png'}`,
    transformation: [
      { raw: 'fo-face,r-max' },
    ],
  })

  return (
    <Image
      source={{ uri }}
      style={[styles.image, { width, height }]}
    />
  )
}

const styles = StyleSheet.create({
  image: {
    borderRadius: '50%',
    backgroundColor: 'darkgray',
  },
})
